spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: yh
    password: yh
    url: jdbc:mysql://localhost/yh?characterEncoding=utf-8&useSSL=false #连接mysql忽略ssl安全协议
  jpa:
    show-sql: true
#  jackson:
#    default-property-inclusion: non_null  #为所有返回参数添加@JsonInclude(JsonInclude.Include.NON_NULL)
server:
  context-path: /sell
#日志配置
logging:
  level: debug
#  pattern:
#    console:
wechat:
  mpAppId: wx135faac6ebc8c2eb
  mpAppSecret: b4163d745a68245ab34924b65722ff09
