spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: yh
    password: yh
    url: jdbc:mysql://localhost/yh?characterEncoding=utf-8&useSSL=false #连接mysql忽略ssl安全协议
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password:
  data:
    elasticsearch:
      cluster-name: my-application
      #集群其他节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点。默认 9300 是 Java 客户端的端口。
      cluster-nodes: 127.0.0.1:9300,127.0.0.1:9301 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode

#  jackson:
#    default-property-inclusion: non_null  #为所有返回参数添加@JsonInclude(JsonInclude.Include.NON_NULL)
server:
  context-path: /sell
  port: 8080
#日志配置
logging:
  level: debug
#    com.lanpang.sell.dataobject.mapper: trance
#  pattern:
#    console:
wechat:
 mpAppId: wx135faac6ebc8c2eb
 mpAppSecret: b4163d745a68245ab34924b65722ff09
 openAppId: wx6ad144e54af67d87
 openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
 mchId: 1483469312
 mchKey: 06C56A89949D617xxxxxxxxxxx
 keyPath: /var/weixin_cert/h5.p12      #证书配置的路径
 notifyUrl: http://6ttfdn.natappfree.cc/sell/pay/notify #异步通知地址 要和项目地址一致
 templateId:
   orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
projectUrl:
  wechatMpAuthorize: f7cwwi.natappfree.cc
  wechatOpenAuthorize: f7cwwi.natappfree.cc
  sell: f7cwwi.natappfree.cc
  loginsource: password #配置是否是密码登录 默认微信登录
mybatis:
  mapper-locations: classpath:/mapper/*.xml